// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnROzLGJ_rTZGb6bzukvfQtkOVcNboJHI',
    appId: '1:456213263795:web:d3048779aee11396d807c6',
    messagingSenderId: '456213263795',
    projectId: 'starcbuck-d4c33',
    authDomain: 'starcbuck-d4c33.firebaseapp.com',
    storageBucket: 'starcbuck-d4c33.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJQb9aQlzHR7BZOHImvALh8E-39wkbvg8',
    appId: '1:456213263795:android:fef64e70ab6629bbd807c6',
    messagingSenderId: '456213263795',
    projectId: 'starcbuck-d4c33',
    storageBucket: 'starcbuck-d4c33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiIvCtP5b1GAI5ZPem6BV93dlGBk2A8Lc',
    appId: '1:456213263795:ios:bf805919b8d687e0d807c6',
    messagingSenderId: '456213263795',
    projectId: 'starcbuck-d4c33',
    storageBucket: 'starcbuck-d4c33.appspot.com',
    iosClientId: '456213263795-gi3u3o5mv0tc3l4jjau24rrh9tbu8arl.apps.googleusercontent.com',
    iosBundleId: 'com.example.starbucks',
  );
}
